### ISSUE TITLE
'x' used for closing looks bad when using Bootstrap

### ISSUE THREAD

**Issue by felixkosmalla** [catc/iGrowl#6]
Hi,

great library, thanks for that. However, when using bootstrap in combination with your plugin the X button looks crappy since it is a button. I used an 'a' instead and it still worked. Are you interested in a pull request or would you mind incorporating it yourself?

Cheers!

**Comment by felixkosmalla** [comment]
and it would need some css tweaking, i.e. no underline when hove and cursor pointer since there would be no target.

**Comment by catc** [comment]
Guess I forgot to account for bootstrap. You can submit a pull request if you'd like, otherwise I'll fix it in a few days.

**Comment by IamCrazyD** [comment]
@felixkosmalla Even I agree.. The design is way too bad while using Bootstrap 3.3.6. I guess @catc has not fixed yet. Eagerly waiting for the fix.
