### ISSUE TITLE
Jquery 2.2

### ISSUE THREAD

**Issue by loveorigami** [catc/iGrowl#8]
I use jquery 2.2 and my bower not updated, because you have   "dependencies":
{
    "jquery": "~2.1.1"
}
Please, update bower to newest jquery version.
Thanks

**Comment by loveorigami** [comment]
Now also package not updated.
You make it for jquery 3.1, but I use 2.2

**Comment by catc** [comment]
I don't understand the what the issue is. If the newest version is 3.1, I'm gonna update to that instead of a previous release...

**Comment by loveorigami** [comment]
Yes, you update as `~3.1` and your package will be available for jquery only for 3.1 (3.1.0 ... 3.1.9...)
I use 2.2 and your package not installed for me and for all, who use jquery <3.1 (2.1, 2.2 .... 2.8, 2.9, 3.0).

Correctly update so `>=2.1` - see PR #9

**Comment by catc** [comment]
Then just upgrade to `3.1` or manually use an older version (it should still work). I'm not change it to `>=2.1` and update it later to `3.1+` just because you're using an older version of jquery.

**Comment by loveorigami** [comment]
I can't update jquery to 3.1, because I use yii framwork.
Jquery 2.2 - it is core for all stable packages (bootstrap, jquery UI...)

After you correct from `~2.1` to `3.1` all people, who use iGrowl with ой 2,1, now have mistake after update. Because `~` - it is for ONLY current version 3.1.

For example - see bower in bootstrap
https://github.com/twbs/bootstrap/blob/master/bower.json#L32
